### ISSUE TITLE
Problems with the pre-pull requests checks

### ISSUE THREAD

**Issue by josemenveg** [vsiakka/gherkin-lint#138]
I've created a pull request #137 and the checks have failed.

The rules are `indentation rule` and `one space between tags rule` which I haven't modified.

If I launch `npm run test` in local it works fine.

Any ideas?

**Comment by josemenveg** [comment]
What I have seen, is that it seems to be a problem with the blank spaces before the tags `@<anything>` and it get more blank spaces.

In local, I get a different node version `v8.11.4` ([the server gets](https://travis-ci.org/vsiakka/gherkin-lint/jobs/456580626) `v11.2.0`) and npm `v5.8.0` (server `v6.4.1`)

**Comment by vsiakka** [comment]
This has been resolved (node 11 changed the behavior of `sort` causing a couple of rules to break)
