### ISSUE TITLE
Feature Request: rules for codeformatting

### ISSUE THREAD

**Issue by timbru31** [vsiakka/gherkin-lint#16]
Hi,

first of all, thanks for the project! 🍻 

Is it possible to add some formatting/code style rules? EditorConfig can fix many of these issue, but it would be better if the linter would throw an error if there are

- trailing spaces
- no newlines at EOF
- consecutive blank lines
- the indention level is wrong

Do you think this is possible to add?

**Comment by vsiakka** [comment]
Hey @timbru31 I can add that, probably this weekend, will keep you posted. Also feel free to make prs if you have any suggested changes/additions ^ ^

**Comment by vsiakka** [comment]
I added rules for all of these with version 0.1.0. Take a look at the documentation of how you configure the rules (https://github.com/vsiakka/gherkin-lint#rule-configuration) because a couple of them give you more options than most rules. 
Let me know if you have any issues :)

**Comment by timbru31** [comment]
Awesome, I'll give it a try later! 🍻
