### ISSUE TITLE
Is there a way to run the linter against one specific rule?

### ISSUE THREAD

**Issue by pr4bh4sh** [vsiakka/gherkin-lint#200]
First of all, Thanks for creating this linter.

Is there any way I can run the tests against a specific rule. Something like this

`gherkin-lint --rule "rule1,rule2" /feature_file_dir`

**Comment by vsiakka** [comment]
Hey @pr4bh4sh! With the current linter interface you can't use a command line parameter to run only a specific rule, however you can create a `.gherkin-lintrc` that only contains one rule and make the linter use that with the `-c` arg. 

Eg, I can have my default linter config which contains many rules in `.gherkin-lintrc`.
When I run `gherkin-lint  /feature_file_dir`, I'll use the rules configured in `.gherkin-lintrc`.
I can also create another file eg `indentation.gherkin-lintrc` only enabling and configuring the indentation rule and run:
`gherkin-lint -c indentation.gherkin-lintrc /feature_file_dir`

Doing it from the command line is a nice feature suggestion for the future.
