### ISSUE TITLE
padEnd is not a function

### ISSUE THREAD

**Issue by yachtdl** [vsiakka/gherkin-lint#204]
> gherkin-lint@3.3.8 demo /Users/user/Documents/Work/gherkin-lint
> node ./dist/main.js -c ./test-data-wip/.gherkin-lintrc test-data-wip/**
/Users/user/Documents/Work/gherkin-lint/dist/formatters/stylish.js:22
  var errorLinePadded = error.line.toString().padEnd(maxLineLength);
                                              ^
TypeError: error.line.toString(...).padEnd is not a function

npm-debug.log -
0 info it worked if it ends with ok
1 verbose cli [ '/Users/user/.nvm/versions/node/v6.11.2/bin/node',
1 verbose cli   '/Users/user/.nvm/versions/node/v6.11.2/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose stack Error: missing script: start
4 verbose stack     at run (/Users/user/.nvm/versions/node/v6.11.2/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /Users/user/.nvm/versions/node/v6.11.2/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /Users/user/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at handleExists (/Users/user/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/read-package-json/read-json.js:329:20)
4 verbose stack     at FSReqWrap.cb [as oncomplete] (fs.js:258:19)
5 verbose cwd /Users/user/Documents/Work/gherkin-lint
6 error Darwin 18.7.0
7 error argv "/Users/user/.nvm/versions/node/v6.11.2/bin/node" "/Users/user/.nvm/versions/node/v6.11.2/bin/npm" "start"
8 error node v6.11.2
9 error npm  v3.10.10
10 error missing script: start
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by vsiakka** [comment]
Fixed with #206 and published with v3.3.9.

Note that this bug only happens in node 6 or prior, whose support has ended for a couple of years ago. I plan on updating the minimum supported version of node for gherkin-lint in the near future, so that it matches the node LTS: https://nodejs.org/en/about/releases/

I will make a major release to make sure i don't cause unintended breakages, but I suggest updating the version of node you use as well.
