### ISSUE TITLE
Update to latest gherkin version

### ISSUE THREAD

**Issue by iamsjn** [vsiakka/gherkin-lint#210]

**Comment by vsiakka** [comment]
I'll check on this again. Last time I tried in the fall there was a bug with the latest gherkin version and some version of node.

**Comment by davidjgoss** [comment]
FWIW cucumber-js recently updated to gherkin 9 and all went smooth

**Comment by davidjgoss** [comment]
FYI decided to have a look at this - it’s meant refactoring most rules as the gherkin document structure has changed a lot. But the tests are good so it’s not too tough. PR soon!

Also the parser is stricter now so some things that used to need rules are just a straight up parse error.

**Comment by vsiakka** [comment]
Hey @davidjgoss , I also started looking into this, I think I'm about 60-70% done, so if you haven't started on it yet, you don't need to. I'll try to finish it this week.

**Comment by davidjgoss** [comment]
@vsiakka no worries will hold off

**Comment by vsiakka** [comment]
Upgrade published with v4.0.0!
