### ISSUE TITLE
Is there any way i can provide the pattern of tags in the allowed tags-

### ISSUE THREAD

**Issue by writetomaha** [vsiakka/gherkin-lint#227]
Hi,

Is there any way i can provide the pattern of tags in the allowed tags, As i would test case numbers in the form of tags example
@TEST_001
@TEST_002

can you suggest how i can provide pattern so that i dont have to provide exact tags in allowed tags.

Thanks In advance
Maha

**Comment by vsiakka** [comment]
Hey @writetomaha , the `allowed-tags` rule doesn't support patterns, so you have to use exact tags.
The rule would have to be changed in order to support that. 

I'd be open to that change, and standardizing all 3 tag related rules  to support patterns, for consistency.

**Comment by writetomaha** [comment]
Hi @vsiakka : Thanks for looking into this issue. It would be really useful if the partial tags can be regularized to support the patterns which i mentioned.

Thanks,
Maha
