### ISSUE TITLE
Bug or feature request

### ISSUE THREAD

**Issue by jlin412** [vsiakka/gherkin-lint#30]
Trying to call it in the grunt task but I am not getting error but not getting error exit code 1 like:

```
Running "gklint" task
/Users/linj/redbox_spa/redbox_angular/test/e2e/features/time/timecard/estimates.feature
  46    Missing Scenario name    no-unamed-scenarios
Done, without errors.
```

Here is my code:

``` javascript
  grunt.registerTask('gklint', function () {
    var done = this.async();
    nodeCommandRunner(['node_modules/gherkin-lint', '.'], done);
  });

  var nodeCommandRunner = function (flags, done) {
    var runner = grunt.util.spawn({
      cmd: 'node',
      args: flags
    }, function() {
      done();
    });

    runner.stdout.pipe(process.stdout);
    runner.stderr.pipe(process.stderr);
  };
```

Did I do something wrong? Or it is a bug?

**Comment by vsiakka** [comment]
I haven't used grunt but judging from this: http://gruntjs.com/api/grunt.util#grunt.util.spawn I don't think you're propagating the exit code of the gherkin-lint process you spawn. I would try changing `nodeCommandRunner` like this:

```javascript
  var nodeCommandRunner = function (flags, done) {
    var runner = grunt.util.spawn({
      cmd: 'node',
      args: flags
    }, function(error, result, code) {
     // propagate the exit code
      done(code);
    });

    runner.stdout.pipe(process.stdout);
    runner.stderr.pipe(process.stderr);
  };
```

If this doesn't work, let me know and I will set up grunt and try it myself.

**Comment by jlin412** [comment]
let me give that a shot

**Comment by jlin412** [comment]
Sorry, I still didn't have time to get to this.  Not sure if I can get around it any time soon.

**Comment by vsiakka** [comment]
I am closing this because I don't think it's an issue with gherkin-lint and the ticket hasn't gotten an update in a year.

**Comment by jlin412** [comment]
It works.  I forget to update.  Thanks.
