### ISSUE TITLE
Switch to ES6

### ISSUE THREAD

**Issue by nene** [vsiakka/gherkin-lint#62]
I've tried to follow the existing code convention of using only ES5 features, but that's kinda painful when you're used to writing ES6 all day. It's also my pet-peeve as I'm the maintainer of [Lebab](http://lebab.io/).

- The obvious route is to use Babel for transpiling the code.
- Another option is to only support Node >= 6. I don't see a required Node version specified in `package.json`, but `.travis.yml` lists all kinds of old versions. Given that gherkin-lint is less than a year old and it's not a library, I doubt there's an actual a need to support these old versions.

Either way, I'm happy to help out with the conversion.

**Comment by vsiakka** [comment]
I added babel to the project a while ago but forgot to updated this. I used lebab for the remaining transformations I wanted to apply with v4.0.1 so I'll call this done!
