### ISSUE TITLE
More user-friendly behavior when running without options

### ISSUE THREAD

**Issue by nene** [vsiakka/gherkin-lint#68]
Currently when you run gherkin-lint in a random directory, you'll get a crash:

```
$ gherkin-lint
/Users/nene/.nvm/versions/node/v6.9.1/lib/node_modules/gherkin-lint/src/config-parser.js:14
      throw new Error('Could not find default config file "' + defaultConfigFileName +'" in the working ' +
      ^

Error: Could not find default config file ".gherkin-lintrc" in the working directory. To use a custom name/location provide the config file using the "-c" arg
    at Object.getConfiguration (/Users/nene/.nvm/versions/node/v6.9.1/lib/node_modules/gherkin-lint/src/config-parser.js:14:13)
    at Object.<anonymous> (/Users/nene/.nvm/versions/node/v6.9.1/lib/node_modules/gherkin-lint/src/main.js:19:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

Luckily the error message tells you exactly what's wrong, but it should be printed without the stack trace.

If you then run gherkin lint in a directory that contains a config file... you'll get no output:

```
$ gherkin-lint
```

This leaves one wondering whether everything perhaps just passed the linter. But in fact you just forgot to specify the feature files to lint. An error message would be in order to point out this mistake. I don't think there's a use-case for running the linter on no files at all.

**Comment by guykisel** [comment]
I feel like reasonable default behavior would be to run on all feature files within the current directory and all child directories.

**Comment by vsiakka** [comment]
These are really good points. I will change the way we handle not having a config file, so that it doesn't show a trace and I like the idea of defaulting to `.` when a features path isn't specified. I'll work on those 2 and the reviews you put up @nene  during the weekned.

**Comment by vsiakka** [comment]
@nene  do you know how i could unit test an exit code?

**Comment by nene** [comment]
Well, I haven't really written tests for exit code by myself, but this should get you started:

- http://stackoverflow.com/questions/32874316/node-js-accessing-the-exit-code-and-stderr-of-a-system-command

I do have written some tests for stdout/stderr:

- https://github.com/lebab/lebab/blob/master/system-test/binTest.js
