### ISSUE TITLE
Support for custom rules

### ISSUE THREAD

**Issue by QuartzBrandi** [vsiakka/gherkin-lint#70]
Hello!

I love that this gherkin linter exists, but I was wondering if there was any planned support for custom rules. I have some very specific app-related things I want to lint for that shouldn't be included in this project, but still would love to lint for.

**Comment by joscha** [comment]
@vsiakka I's be highly interested in this as well - any chance we can make this happen? Maybe an initial flag that allows to specify an additional rule directory where rules are picked up from? Happy to provide that as a PR.

**Comment by vsiakka** [comment]
@joscha feel free to put a PR if you want! Otherwise if I get some time this weekend and I can look into it too, it should be pretty easy, the rules have a uniform api already so it's just a matter of looking in more paths.

**Comment by joscha** [comment]
👍 Opened #75 @vsiakka

**Comment by vsiakka** [comment]
@QuartzBrandi @joscha -> Joscha's PR that addresses this has been released with v2.3.0
