### ISSUE TITLE
don't find .feature files 

### ISSUE THREAD

**Issue by AlfredoMoretta** [vsiakka/gherkin-lint#71]
it works perfectly if i pass the exact path...but if i launch only the command don't work properly (don't return anything...simply return the shell )

**Comment by vsiakka** [comment]
@AlfredoMoretta  are you running `gherkin-lint .`? Gherkin lint expects a path in the input even if it's the current path. It will find recursively all files in the specified path. I can change the default behavior to use the current directory as the search directory.

**Comment by AlfredoMoretta** [comment]
@vsiakka i've tried but didn't work for me. I've a Feature folder and inside it a lot of subfolder with .features file. i pass the exact path but the error i had always is " throw new Error('Invalid input format. To run the linter please specify a feature file, directory or glob.');" .If i pass the exact path with single feature it work...tell me if i can help with other information and thank you for the support

**Comment by nene** [comment]
I'd suggest making Gherkin-lint accept any number of files/directories as
input parameters. Files would be linted, directories scanned for .feature
files.

And it wouldn't even be a breaking change to the API :)

30.05.2017 3:32 AM kirjutas kuupäeval "Alfredo Moretta" <
notifications@github.com>:

**Comment by vsiakka** [comment]
Sorry for the really delayed fix. I found the issue: your path was probably not ending in '\' and so it wasn't identified as a directory. I made a change that correctly identifies existing directories as such, regardless of whether they end on '\' or not.

**Comment by vsiakka** [comment]
The fix is available in v2.2.0

**Comment by ajuram-salim** [comment]
Gherkin-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: restqa/gherkin-linter-action@0.0.1
        with:
          path: "D:/a/4pl-neonav-testautomation/4pl-neonav-testautomation/src/test/resources/features/MaerskStaging/"
          config_file: 'D:/a/4pl-neonav-testautomation/4pl-neonav-testautomation/src/test/resources/features/MaerskStaging/.gherkin-lintrc'


But i am getting error on github actions :

Invalid format of the feature file path/pattern: "D:/a/4pl-neonav-testautomation/4pl-neonav-testautomation/src/test/resources/features/MaerskStaging/".

        To run the linter please specify an existing feature file, directory or glob.
