### ISSUE TITLE
Unable to turn off rule in array, says off isnt a valid option

### ISSUE THREAD

**Issue by gd46** [vsiakka/gherkin-lint#73]
For example: 

"name-length" : ["off", { "Feature": 70, "Scenario": 70, "Step": 70 }]

Throws console error saying that the only valid options are on or off.

**Comment by vsiakka** [comment]
Thanks for reporting the bug and the PR to fix it (boy was that stupid :X, my mistake i mean, your fix is great).
I merged and published your fix with v2.2.1!

**Comment by gd46** [comment]
No worries, great! Thanks
