### ISSUE TITLE
Limit the size of scenarios

### ISSUE THREAD

**Issue by honzajavorek** [vsiakka/gherkin-lint#94]
Long scenarios are hard to read and they're a _smell_ indicating there's something wrong with the approach you took when writing the Gherkins. It would be nice to have a rule ensuring the scenarios have no more than X steps. Analogous to [cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity) of code.

**Comment by josemenveg** [comment]
A question:
How "long" is a scenario?
1) number of steps in a scenario (or background)
2) scenario steps + background steps

I have excluded the examples, I think that it has no sense include them.

**Comment by honzajavorek** [comment]
That is a good question.

Personally, I tend to believe that while Background is obviously making the scenarios longer in total, it does lower the cognitive complexity of the scenarios, because one needs to read the common setup just once and then just keeps it in memory while reading the rest.

For that reason, I would consider Backgrounds with many steps to be long, as well as Scenarios with many steps, but I would not sum the steps, although it seems like an obvious thing to do. Because sometimes human brain doesn't work obvious ways 😄 

I think the answer is 1.

**Comment by josemenveg** [comment]
I've created a pull to cover it.

The new rule 'scenario-size' let specify a maximum step length for the scenario (or scenario outline) and the bacground.

You can check it in my fork.

**Comment by vsiakka** [comment]
`scenario-size` rule has been published with v3.2.0
